name: Build and Deploy MkDocs Material (Reloaded)
description: Builds and/or Deploys MkDocs Material to GitHub Pages, or a Directory

inputs:
  mkdocs-version:
    type: string
    required: false
    default: "latest"
    description: "MkDocs version to use"
  requirements:
    type: string
    required: false
    default: "./docs/requirements.txt"
    description: "Path to the requirements.txt file"
  config-file:
    type: string
    required: false
    default: "mkdocs.yml"
    description: "Path to the mkdocs.yml file"
  publish-to-pages:
    type: boolean
    required: false
    default: true
    description: "Whether to publish to GitHub Pages"
  checkout-current-repo:
    type: boolean
    required: false
    default: true
    description: "Whether to perform repository checkout"
  pre-build-script:
    type: string
    required: false
    description: "Path to the pre-build script"
  pre-build-shell:
    type: string
    required: false
    default: "bash"
    description: "Shell to use for running the pre-build script"
  output-directory:
    type: string
    required: false
    default: "./site"
    description: "Custom output directory for the MkDocs build"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      if: ${{ inputs.checkout-current-repo }}
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Setup Pages
      if: ${{ inputs.publish-to-pages }}
      id: pages
      uses: actions/configure-pages@v4

    - name: Install MkDocs and Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ "${{ inputs.mkdocs-version }}" = "latest" ]; then
          pip install mkdocs-material
        else
          pip install mkdocs-material==${{ inputs.mkdocs-version }}
        fi
        if [ -f "${{ inputs.requirements }}" ]; then
          pip install -r "${{ inputs.requirements }}"
        fi

    - name: Run Pre-build Script
      if: ${{ inputs.pre-build-script }}
      shell: ${{ inputs.pre-build-shell }}
      run: |
        if [ -f "${{ inputs.pre-build-script }}" ]; then
          ${{ inputs.pre-build-shell }} "${{ inputs.pre-build-script }}"
        fi

    - name: Build MkDocs Site
      shell: bash
      run: mkdocs build --config-file "${{ inputs.config-file }}" --site-dir "${{ inputs.output-directory }}"

    - name: Upload pages artifact
      if: ${{ inputs.publish-to-pages }}
      uses: actions/upload-pages-artifact@v3
      with:
        name: "github-pages"
        path: "${{ inputs.output-directory }}"

    - name: Deploy to GitHub Pages
      if: ${{ inputs.publish-to-pages }}
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: "github-pages"