name: Test MkDocs Workflow

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Reloaded-Project/Reloaded.MkDocsMaterial.Themes.R2
          submodules: 'recursive'

      - name: Deploy MkDocs
        uses: Reloaded-Project/devops-mkdocs@v1
        with:
          REQUIREMENTS: docs/requirements.txt